{% set name = "django-safedelete" %}
{% set version = "1.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: ce63f2dd101fec303837ef624592628e022691c3ade2a0893c9fc4c7796e8288

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django
    - python >=3.6

test:
  commands:
    - pip check
    # django settings configuration must be setup before safedelete can be imported
    - python -c "from django.conf import settings;settings.configure();import safedelete"
  requires:
    - pip

about:
  home: https://github.com/makinacorpus/django-safedelete
  summary: Mask your objects instead of deleting them from your database.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MichelML
